### ISSUE TITLE
can you decode also LB files too ??

### ISSUE THREAD

**Issue by m0hamedessam** [Rubensigner/xtream-codes-decoded#10]
can you decode also LB files too ??

**Comment by Rubensigner** [comment]
Unfortunately not at the moment, I'm still decoding the main one.

**Comment by m0hamedessam** [comment]
Do you have good tool to remove at least obfuscation from files for now i tried many but all not accurate

**Comment by Rubensigner** [comment]
**The obfuscation of files was not removed by me**
The obfuscation was removed by: https://github.com/tweakunwanted
**See the description of the project that I explain.**

**Comment by Rubensigner** [comment]
What I am doing is renaming all the names of variables, functions and classes in the code.

**Comment by m0hamedessam** [comment]
I knew and i open topic there already and waiting his answer but just ask maybe you know good tool..

**Comment by Rubensigner** [comment]
Unfortunately I don't have the tool he used to do this.
